# Generated by Django 6.1.1 on 2026-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='সমস্যার শিরোনাম (যেমন: পিসি নষ্ট)')),
                ('description', models.TextField(verbose_name='বিস্তারিত বিবরণ')),
                ('image', models.ImageField(upload_to='complaints/', verbose_name='সমস্যার ছবি')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
